#pragma once

#include <wlsp/types/applyWorkspaceEdit.hpp>
#include <wlsp/types/cancelParams.hpp>
#include <wlsp/types/codeAction.hpp>
#include <wlsp/types/codeLens.hpp>
#include <wlsp/types/colorPresentation.hpp>
#include <wlsp/types/command.hpp>
#include <wlsp/types/completion.hpp>
#include <wlsp/types/configuration.hpp>
#include <wlsp/types/declaration.hpp>
#include <wlsp/types/definition.hpp>
#include <wlsp/types/diagnostic.hpp>
#include <wlsp/types/didChangeConfiguration.hpp>
#include <wlsp/types/didChangeTextDocument.hpp>
#include <wlsp/types/didChangeWatchedFiles.hpp>
#include <wlsp/types/didChangeWorkspaceFolders.hpp>
#include <wlsp/types/didCloseTextDocument.hpp>
#include <wlsp/types/didOpenTextDocument.hpp>
#include <wlsp/types/didSaveTextDocument.hpp>
#include <wlsp/types/documentColor.hpp>
#include <wlsp/types/documentFilter.hpp>
#include <wlsp/types/documentFormatting.hpp>
#include <wlsp/types/documentHighlight.hpp>
#include <wlsp/types/documentLink.hpp>
#include <wlsp/types/documentOnTypeFormatting.hpp>
#include <wlsp/types/documentRangeFormatting.hpp>
#include <wlsp/types/documentSymbol.hpp>
#include <wlsp/types/executeCommand.hpp>
#include <wlsp/types/fileResourceChanges.hpp>
#include <wlsp/types/foldingRange.hpp>
#include <wlsp/types/genericObject.hpp>
#include <wlsp/types/hover.hpp>
#include <wlsp/types/implementation.hpp>
#include <wlsp/types/initialize.hpp>
#include <wlsp/types/jsonTypes.hpp>
#include <wlsp/types/location.hpp>
#include <wlsp/types/locationLink.hpp>
#include <wlsp/types/logMessage.hpp>
#include <wlsp/types/markupContent.hpp>
#include <wlsp/types/message.hpp>
#include <wlsp/types/objectT.hpp>
#include <wlsp/types/partialResult.hpp>
#include <wlsp/types/position.hpp>
#include <wlsp/types/publishDiagnostic.hpp>
#include <wlsp/types/range.hpp>
#include <wlsp/types/reference.hpp>
#include <wlsp/types/registration.hpp>
#include <wlsp/types/rename.hpp>
#include <wlsp/types/requestMessage.hpp>
#include <wlsp/types/responseMessage.hpp>
#include <wlsp/types/selectionRange.hpp>
#include <wlsp/types/showMessage.hpp>
#include <wlsp/types/signatureHelp.hpp>
#include <wlsp/types/staticRegistration.hpp>
#include <wlsp/types/textDocumentIdentifier.hpp>
#include <wlsp/types/textDocumentItem.hpp>
#include <wlsp/types/textDocumentPosition.hpp>
#include <wlsp/types/textDocumentRegistration.hpp>
#include <wlsp/types/textDocumentSync.hpp>
#include <wlsp/types/textEdit.hpp>
#include <wlsp/types/typeDefinition.hpp>
#include <wlsp/types/willSaveTextDocument.hpp>
#include <wlsp/types/workDoneProgress.hpp>
#include <wlsp/types/workspaceEdit.hpp>
#include <wlsp/types/workspaceFolder.hpp>
#include <wlsp/types/workspaceSymbol.hpp>
